blank_issues_enabled: false
contact_links:
  - name: Dashboards Support Discord Server
    url: https://discordapp.com/invite/78h7xgj
    about: Please ask and answer general questions here. Issues are meant for bug reports or feature requests.
